export class Ease {
  static LINEAR = 'linear'
  static SMOOTHSTEP = 'smoothstep'
  static SMOOTHSTEP_SQUARED = 'smoothstepSquared'
  static SMOOTHSTEP_CUBED= 'smoothstepCubed'
  static ACCESELARION = 'acceleration'
  static ACCELERATION_CUBED = 'accelerationCubed'
  static DECELERATION = 'deceleration'
  static DECELERATION_CUBED = 'decelerationCubed'
  static SINE = 'sine'
  static SINE_SQUARED = 'sineSquared'
  static SINE_CUBED = 'sineCubed'
  static INVERSE_SINE = 'inverseSine'
  static INVERSE_SINE_SQUARED = 'inverseSineSquared'
  static INVERSE_SINE_CUBED = 'inverseSineCubed'
  static SPLINE = 'spline'
  static CUBIC_BEZIER = 'cubicBezier'
}
